# Creating an nd array 

In [2]:
import numpy as np 
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


# Multi-Dimensional Array

In [17]:
ab=np.array([[1,2,3,4,5,6],[7,8,9,4,5,6]])
print(ab)

[[1 2 3 4 5 6]
 [7 8 9 4 5 6]]


# Choice array in NumPy

In [2]:
b=np.full((3,3),5)
print(b)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


# Random array

In [5]:
c=np.random.rand(5,2)
print(c)

[[0.46185398 0.41067398]
 [0.03863765 0.39578355]
 [0.19680597 0.77695624]
 [0.57069562 0.30567407]
 [0.21976809 0.54216369]]


# Array of Zeros

In [12]:
d=np.zeros((5,5),dtype=np.int32)
print(d)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


# Array of Ones

In [11]:
e=np.ones((8,8),dtype=np.int32)
print(e)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


# Imatrix array 

In [7]:
f=np.eye(5,k=-2)
print(f)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# Evenly Spaced Arrays

In [3]:
g=np.arange(2,10,4,dtype=np.int32)
print(g)

[2 6]


In [14]:
x=np.arange(24).reshape(2,3,4)
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# Linspace Array

In [8]:
h=np.linspace(0,1,5)
print(h)

[0.   0.25 0.5  0.75 1.  ]
