# Slicing N-Dimensional Arrays

Slicing a Single Dimensional Array

In [6]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
a[1:10:2]

array([ 2,  4,  6,  8, 10])

Slicing a 2-Dimensional Array

In [33]:
b=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(b[:2])

[[10 20 30]
 [40 50 60]]


In [45]:
import numpy as np
np.random.seed(111)
a=np.random.randint(1,500,30).reshape(6,5)
a

array([[341, 365, 469, 213,  87],
       [276, 170, 323, 119, 467],
       [297, 456, 442,   8, 269],
       [267, 450, 369, 217, 285],
       [271, 419,  22,  55, 201],
       [ 38, 461, 231, 187, 269]])

In [42]:
a[2:,2:]

array([[442,   8, 269],
       [369, 217, 285],
       [ 22,  55, 201],
       [231, 187, 269]])

In [35]:
a[3:5,2:]

array([[[28, 29],
        [30, 31]]])

In [31]:
b=np.arange(24).reshape(4,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [33]:
print(b[2:3,3:5])


[[15 16]]


Slicing a 3-Dimensional Array

In [8]:
a=np.arange(32).reshape(4,4,2)
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]
  [30 31]]]


So we have 4 layers, 4 rows and 2 columns

In [15]:
print(a[2:3,1:3,0:1])

[[[18]
  [20]]]


In [37]:
print(a[1:2,::,::])

[[[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]


In [30]:
print(a[1:2,3:4,1:2])

[[[15]]]


# Negative Slicing

In order to satisfy Backward approach we use NEgative numbers

In [38]:
x=np.random.randint(0,24,12)
x

array([17, 21, 22, 20, 20,  4, 10, 11,  8,  5,  9, 17])

In [50]:
print(x[-(2*3)])

10


Flipping the array using neagtive slicing

In [63]:
a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
print('Original array :','\n',a[::1,::1])
print('Reversed array :','\n',a[::1,::-1])

Original array : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Reversed array : 
 [[ 5  4  3  2  1]
 [10  9  8  7  6]]


Flipping the array using flip method

In [75]:
print("The Original Array \n ",a,"\n")
print("Flipping Horizontally \n",np.flip(a,axis=0))
print("\n Flipping Vertically\n",np.flip(a,axis=1))

The Original Array 
  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

Flipping Horizontally 
 [[ 6  7  8  9 10]
 [ 1  2  3  4  5]]

 Flipping Vertically
 [[ 5  4  3  2  1]
 [10  9  8  7  6]]


In [76]:
b = np.array([[2],[2]])
b

array([[2],
       [2]])

# Stacking and Concatenation of Arrays

Horizontal Stacking

In [13]:
a=np.random.randint(1,30,8)
b=np.random.randint(1,30,8)
print(a,"\n",b)
a=np.hstack((a,b))
print("Horizontal Stacking \n",a)

[13 10  4 20 21 17 11 21] 
 [19  4  1  8  1 11 17  2]
Horizontal Stacking 
 [13 10  4 20 21 17 11 21 19  4  1  8  1 11 17  2]


Vertical Stacking

In [15]:
a=np.random.randint(1,30,8)
b=np.random.randint(1,30,8)
print(a,"\n",b)
b=np.vstack((a,b))
print("Vertical Stacking \n",b)

[20 15 26 15 10 26 27 22] 
 [26  5 16 14 25 12  5 23]
Vertical Stacking 
 [[20 15 26 15 10 26 27 22]
 [26  5 16 14 25 12  5 23]]


Depth Stacking

In [32]:
a=np.random.randint(1,30,12).reshape(3,2,2)
b=np.random.randint(30,60,12).reshape(3,2,2)
c=np.random.randint(30,60,12).reshape(3,2,2)
print(a,"\n",b,"\n",c,"\n","Depth Stacking")
print("\n",np.dstack((a,b,c)))

[[[16 26]
  [21 20]]

 [[28  3]
  [18  4]]

 [[22 28]
  [ 9 18]]] 
 [[[54 37]
  [57 37]]

 [[45 34]
  [34 57]]

 [[35 52]
  [54 46]]] 
 [[[58 52]
  [37 34]]

 [[48 50]
  [47 31]]

 [[31 41]
  [43 46]]] 
 Depth Stacking

 [[[16 26 54 37 58 52]
  [21 20 57 37 37 34]]

 [[28  3 45 34 48 50]
  [18  4 34 57 47 31]]

 [[22 28 35 52 31 41]
  [ 9 18 54 46 43 46]]]


# Contenation of nd-arrays

In [8]:
a=np.arange(0,5).reshape(1,5)
b=np.arange(5,10).reshape(1,5)
print("Horizontal Concatenation")
print(np.concatenate((a,b),axis=0))

Horizontal Concatenation
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
a=np.arange(0,5).reshape(1,5)
b=np.arange(5,10).reshape(1,5)
print("Vertical Concatenation")
print(np.concatenate((a,b),axis=1))

Vertical Concatenation
[[0 1 2 3 4 5 6 7 8 9]]


Append() method

In [21]:
a=np.array([[1,2,3,4,5,6]])
np.append(a,[[8,7,9,87,45,25478]],axis=0)

array([[    1,     2,     3,     4,     5,     6],
       [    8,     7,     9,    87,    45, 25478]])