# Splitings in n-d array

In [9]:
import numpy as np
import pandas as pd

In [29]:
a=np.random.randint(0,99,12).reshape(3,4)
print(a)
np.split(a,4,axis=1)

[[43 22 94 85]
 [18 17 67 94]
 [95 43 86 21]]


[array([[43],
        [18],
        [95]]),
 array([[22],
        [17],
        [43]]),
 array([[94],
        [67],
        [86]]),
 array([[85],
        [94],
        [21]])]

In [30]:
a=np.random.randint(0,99,12).reshape(3,4)
print(a)
np.split(a,3,axis=0)

[[88 48 65 31]
 [43 84 28 75]
 [33 84  0 67]]


[array([[88, 48, 65, 31]]),
 array([[43, 84, 28, 75]]),
 array([[33, 84,  0, 67]])]

# Horizontal split

Using this method There is no need of mentioning about axis

In [38]:
a=np.random.randint(0,99,12).reshape(3,4)
print(a)
np.hsplit(a,4)

[[57 54  0 74]
 [92  3 59 65]
 [15 79 34 26]]


[array([[57],
        [92],
        [15]]),
 array([[54],
        [ 3],
        [79]]),
 array([[ 0],
        [59],
        [34]]),
 array([[74],
        [65],
        [26]])]

# Vertical Split

In [37]:
a=np.random.randint(0,99,12).reshape(3,4)
print(a)
np.vsplit(a,3)

[[95 14 93 96]
 [25 69 85 72]
 [42 85 68 41]]


[array([[95, 14, 93, 96]]),
 array([[25, 69, 85, 72]]),
 array([[42, 85, 68, 41]])]